#! /usr/bin/env python3

import subprocess

subprocess.run(["gdb", "-x", "gdb_script.py", "traceme"],
               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

with open("./my_called_functions", "r") as file:
    print(file.read())
